# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/client.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usertable = QtWidgets.QTableView(self.centralwidget)
        self.usertable.setObjectName("usertable")
        self.gridLayout.addWidget(self.usertable, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userinput = QtWidgets.QLineEdit(self.centralwidget)
        self.userinput.setObjectName("userinput")
        self.horizontalLayout.addWidget(self.userinput)
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setObjectName("sendbutton")
        self.horizontalLayout.addWidget(self.sendbutton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 2)
        self.chattextbox = QtWidgets.QTextBrowser(self.centralwidget)
        self.chattextbox.setObjectName("chattextbox")
        self.gridLayout.addWidget(self.chattextbox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.chattextbox.append("안동기: 우리는 자습실에서 채팅을 할 권리가 있습니다!")
        self.chattextbox.append("조용히 해라!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "블루투스 채팅 클라이언트"))
        self.sendbutton.setText(_translate("MainWindow", "전송"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
